name: Deploy to Linode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          # Install the private key
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Trust both your domain and the raw IP
          ssh-keyscan -H zebekov.mk          >> ~/.ssh/known_hosts
          ssh-keyscan -H 172.104.146.103     >> ~/.ssh/known_hosts

      - name: Deploy on server
        run: |
          ssh -i ~/.ssh/id_ed25519 root@172.104.146.103 << 'EOF'
            set -e
            cd /var/www/zebekov
            git pull origin main
            npm install
            npm run build
            pm2 restart zebekov-webapp
          EOF
